all:
  children:
    # --- リモート管理対象サーバー (ラズベリーパイ) ---
    rpis:
      hosts:
        fedora-pi:
          ansible_host: 192.168.1.151
        almalinux-pi:
          ansible_host: 192.168.1.152
      vars:
        ansible_user: ansible
        ansible_python_interpreter: /usr/bin/python3

    # --- Windows開発端末 ---
    windows:
      hosts:
        windows11dev:
          ansible_host: 192.168.1.200
      vars:
        ansible_user: ansibled
        ansible_connection: ssh
        ansible_shell_type: powershell

    # --- 母艦サーバー自身 (ローカル実行用) ---
    local:
      hosts:
        localhost:
      vars:
        ansible_connection: local
        ansible_python_interpreter: /usr/bin/python3
