---
monitoring_arch: linux-amd64

prometheus_version: "2.55.1"
prometheus_user: prometheus
prometheus_group: prometheus
prometheus_install_dir: /opt/prometheus
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus
prometheus_listen_address: "127.0.0.1:9091"
prometheus_retention_time: 30d
prometheus_scrape_interval: 15s
prometheus_evaluation_interval: 15s
prometheus_scrape_targets:
  - job_name: prometheus
    targets:
      - localhost:9091
  - job_name: node
    targets:
      - localhost:9100

node_exporter_version: "1.8.2"
node_exporter_user: node_exporter
node_exporter_group: node_exporter
node_exporter_install_dir: /opt/node_exporter
node_exporter_listen_address: "127.0.0.1:9100"

grafana_manage_repo: true
grafana_package_name: grafana
grafana_http_addr: "0.0.0.0"
grafana_http_port: 3000
grafana_admin_user: admin
grafana_admin_password: admin
grafana_prometheus_datasource_name: Prometheus
grafana_prometheus_datasource_url: http://127.0.0.1:9091
grafana_allow_network_connect_selinux: true
grafana_selinux_booleans:
  - grafana_can_tcp_connect_prometheus_port
  - httpd_can_network_connect
prometheus_selinux_port_type: prometheus_port_t
prometheus_selinux_port: 9091

monitoring_configure_firewalld: true
monitoring_firewalld_ports:
  - 3000/tcp
